repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.0  # or whichever version you want
    hooks:
      - id: clang-format
        args: [--style=file]
        files: \.(cpp|hpp|c|h)$